import { useState } from "react";
import { Header } from "@/components/Header";
import { FileUpload } from "@/components/FileUpload";
import { QuizInterface } from "@/components/QuizInterface";
import { NotesDisplay } from "@/components/NotesDisplay";
import { Dashboard } from "@/components/Dashboard";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { BookOpen, FileText, BarChart3, Upload, Youtube } from "lucide-react";

const Index = () => {
  const [activeTab, setActiveTab] = useState("upload");
  const [selectedFile, setSelectedFile] = useState<File | null>(null);

  const handleFileSelect = (file: File) => {
    setSelectedFile(file);
    // Auto-switch to notes tab after file selection
    setActiveTab("notes");
  };

  const features = [
    {
      icon: Upload,
      title: "Smart File Upload",
      description: "Upload PDFs, images, or text files for AI-powered analysis"
    },
    {
      icon: BookOpen,
      title: "AI Notes & Mind Maps", 
      description: "Get concise notes and visual mind maps generated by AI"
    },
    {
      icon: FileText,
      title: "Interactive Quizzes",
      description: "Test your knowledge with AI-generated MCQs and explanations"
    },
    {
      icon: BarChart3,
      title: "Performance Tracking",
      description: "Monitor your learning progress and identify weak areas"
    },
    {
      icon: Youtube,
      title: "Video Recommendations",
      description: "Get relevant YouTube videos based on your study topics"
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-accent/10 to-background">
      <Header />
      
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {!selectedFile ? (
          // Welcome Section
          <div className="text-center space-y-8 py-12">
            <div className="space-y-4">
              <h1 className="text-5xl font-bold bg-gradient-to-r from-primary via-primary-glow to-primary bg-clip-text text-transparent">
                EduGenie Hub
              </h1>
              <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
                Transform your learning with AI-powered notes, quizzes, and personalized study recommendations
              </p>
            </div>

            {/* Features Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
              {features.map((feature, index) => (
                <Card key={index} className="bg-card/50 backdrop-blur-sm border-border/50 hover:border-primary/50 transition-all duration-300 hover:shadow-lg">
                  <CardContent className="p-6 text-center space-y-3">
                    <div className="w-12 h-12 bg-gradient-to-r from-primary to-primary-glow rounded-lg mx-auto flex items-center justify-center">
                      <feature.icon className="w-6 h-6 text-primary-foreground" />
                    </div>
                    <h3 className="font-semibold">{feature.title}</h3>
                    <p className="text-sm text-muted-foreground">{feature.description}</p>
                  </CardContent>
                </Card>
              ))}
            </div>

            {/* File Upload Section */}
            <div className="max-w-2xl mx-auto">
              <FileUpload onFileSelect={handleFileSelect} />
            </div>

            {/* Demo Section */}
            <Card className="max-w-4xl mx-auto mt-12">
              <CardHeader>
                <CardTitle>Experience EduGenie</CardTitle>
                <CardDescription>
                  Explore our features with sample content while you set up your backend
                </CardDescription>
              </CardHeader>
              <CardContent>
                <Tabs defaultValue="dashboard" className="w-full">
                  <TabsList className="grid w-full grid-cols-3">
                    <TabsTrigger value="dashboard">Dashboard</TabsTrigger>
                    <TabsTrigger value="notes">Sample Notes</TabsTrigger>
                    <TabsTrigger value="quiz">Try Quiz</TabsTrigger>
                  </TabsList>
                  <TabsContent value="dashboard" className="mt-6">
                    <Dashboard />
                  </TabsContent>
                  <TabsContent value="notes" className="mt-6">
                    <NotesDisplay topic="Sample Learning Materials" />
                  </TabsContent>
                  <TabsContent value="quiz" className="mt-6">
                    <QuizInterface topic="General Knowledge" />
                  </TabsContent>
                </Tabs>
              </CardContent>
            </Card>
          </div>
        ) : (
          // Main App Interface
          <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
            <TabsList className="grid w-full grid-cols-4">
              <TabsTrigger value="upload">Upload</TabsTrigger>
              <TabsTrigger value="notes">Notes</TabsTrigger>
              <TabsTrigger value="quiz">Quiz</TabsTrigger>
              <TabsTrigger value="dashboard">Dashboard</TabsTrigger>
            </TabsList>

            <TabsContent value="upload" className="mt-6">
              <FileUpload onFileSelect={handleFileSelect} />
            </TabsContent>

            <TabsContent value="notes" className="mt-6">
              <NotesDisplay topic={selectedFile?.name} />
            </TabsContent>

            <TabsContent value="quiz" className="mt-6">
              <QuizInterface topic={selectedFile?.name} />
            </TabsContent>

            <TabsContent value="dashboard" className="mt-6">
              <Dashboard />
            </TabsContent>
          </Tabs>
        )}
      </main>
    </div>
  );
};

export default Index;
