import { useNavigate } from 'react-router-dom';
import { BookOpen, FileText, BarChart3, Upload, Youtube } from "lucide-react";

const features = [
  {
    icon: Upload,
    title: "Smart File Upload",
    description: "Upload PDFs, images, or text files for AI-powered analysis"
  },
  {
    icon: BookOpen,
    title: "AI Notes & Mind Maps",
    description: "Get concise notes and visual mind maps generated by AI"
  },
  {
    icon: FileText,
    title: "Interactive Quizzes",
    description: "Test your knowledge with AI-generated MCQs and explanations"
  },
  {
    icon: BarChart3,
    title: "Performance Tracking",
    description: "Monitor your learning progress and identify weak areas"
  },
  {
    icon: Youtube,
    title: "Video Recommendations",
    description: "Get relevant YouTube videos based on your study topics"
  },
  {
    icon: FileText,
    title: "Personalized Learning",
    description: "AI tailors your study plan and quiz difficulty to your needs"
  },
  {
    icon: BookOpen,
    title: "Instant Explanations",
    description: "Get clear explanations and study tricks for tough concepts"
  }
];

const Index = () => {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-accent/10 to-background flex flex-col items-center justify-center">
      <div className="text-center space-y-8 py-16">
        <div className="space-y-4">
          <h1 className="text-5xl font-extrabold text-purple-500 mb-2">EduGenie Hub</h1>
          <p className="text-xl text-gray-700 max-w-2xl mx-auto">
            Transform your learning with AI-powered notes, quizzes, mind maps, and personalized study recommendations.<br/>
            Upload your study materials and let AI do the rest—get instant notes, quizzes, explanations, and video suggestions to boost your performance!
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8 mt-8">
          {features.map((feature, index) => (
            <div key={index} className="bg-white rounded-xl shadow p-6 flex flex-col items-center hover:shadow-lg transition-all">
              <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mb-3">
                <feature.icon className="w-6 h-6 text-purple-500" />
              </div>
              <h3 className="font-semibold text-lg mb-1">{feature.title}</h3>
              <p className="text-sm text-gray-500">{feature.description}</p>
            </div>
          ))}
        </div>
        <button
          className="mt-8 px-8 py-3 bg-purple-600 text-white rounded-lg text-lg font-semibold shadow hover:bg-purple-700 transition"
          onClick={() => navigate('/login')}
        >
          Start Now
        </button>
      </div>
    </div>
  );
};

export default Index;
